### ISSUE TITLE
离线版下载安装报毒

### ISSUE THREAD

**Issue by OfflineY** [burgerstudio/burgerstudio.github.io#1]
如题
另外，感觉作者的网站很棒，想加个友链
https://yuanyubo-studio.vercel.app/

**Comment by Offline2008** [comment]
突然感觉自己的主页功能好少😂

**Comment by burgerstudio** [comment]
已加友链，在“网络站点”页面里

在 2022年2月9日，14:33，Offline2008 ***@***.******@***.***>> 写道：


yuanyubo-studio.vercel.app<https://yuanyubo-studio.vercel.app/>

**Comment by origx** [comment]
已添加到每页页脚😀
